parameters:
  - name: workingDirectory
    type: string
  - name: pythonVersion
    type: string

steps:
  - task: UsePythonVersion@0
    displayName: Run Azure Machine Learning Experiment
    inputs:
      versionSpec: ${{ parameters.pythonVersion }}
      architecture: x64

  - script: |
      echo ${AZURE_SUBSCRIPTION_ID}
      echo ${AZURE_CLIENT_ID}
      echo ${AZURE_CLIENT_SECRET}
      echo ${AZURE_TENANT_ID}
      echo ${AZURE_RESOURCE_GROUP}
      echo ${AZURE_WORKSPACE_NAME}
      echo ${DATASTORE_NAME}
    displayName: 'Echo Azure Environment Variables'
  
  - script: |
      echo "Logging into Azure..."
      az login --service-principal \
        --username "$AZURE_CLIENT_ID" \
        --password "$AZURE_CLIENT_SECRET" \
        --tenant "$AZURE_TENANT_ID"
      az account set --subscription "$AZURE_SUBSCRIPTION_ID"
    displayName: 'Azure Login'

  - bash: |
      pip install uv
      uv sync
      uv pip install azureml-core==1.60.0
      uv pip install azure-ai-ml==1.27.1
      uv pip install xlrd==2.0.1
      uv pip install azureml-fsspec==1.3.1
      uv pip install azureml-dataprep==5.1.6
      uv pip install pandas==2.2.3
      uv pip install setuptools==80.9.0
      uv pip install scikit-learn==1.6.1
      uv pip install python-dotenv==1.1.0
      uv pip install openpyxl==3.1.5
    workingDirectory: ${{ parameters.workingDirectory }}
    displayName: 'Install dependencies'

  - bash: |
      uv run ${{ parameters.workingDirectory }}/tests/aml_experiment/evaluate_metrics.py
    displayName: 'Evaluate experiment metrics'
    workingDirectory: ${{ parameters.workingDirectory }}

  - bash: |
      echo "##vso[task.setvariable variable=model_approved;isOutput=true]$(cat model_approved.txt)"
      echo "Model approved: $(cat model_approved.txt)"
    displayName: 'Set model approval variable'

  - bash: |
      if [ ! -f model_approved.txt ]; then
        echo "model_approved.txt not found!"
        exit 1
      fi
      MODEL_APPROVED=$(cat model_approved.txt)
      echo "##vso[task.setvariable variable=model_approved;isOutput=true]$MODEL_APPROVED"
      echo "Model approved: $MODEL_APPROVED"
      if [ "$MODEL_APPROVED" != "true" ]; then
        echo "Model not approved. Failing the step."
        exit 1
      fi
    displayName: 'Set model approval variable and check approval'